name: composite action test

on:
  push:

jobs:
  composite-action:
    name: job to test composite action
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5.0.0
      - uses: ./
        id: compositeAction
        with:
          number1: 5
          number2: 4
      - run: echo ${{ steps.compositeAction.outputs.result }}
